### ISSUE TITLE
train matter

### ISSUE THREAD

**Issue by 201814476285951** [CapsuleEndoscope/EndoSLAM#20]
/home/dell/anaconda3/envs/endoslam/bin/python /home/dell/EndoSLAM/EndoSfMLearner/train.py --name /home/dell/EndoSLAM/EndoSfMLearner/train
=> will save everything to /home/dell/EndoSLAM/EndoSfMLearner/train/03-21-22:36
=> fetching scenes in '/home/dell/EndoSLAM/EndoSfMLearner/Data_Path'
Traceback (most recent call last):
  File "/home/dell/EndoSLAM/EndoSfMLearner/train.py", line 456, in <module>
    main()
  File "/home/dell/EndoSLAM/EndoSfMLearner/train.py", line 113, in main
    dataset=args.dataset
  File "/home/dell/EndoSLAM/EndoSfMLearner/datasets/sequence_folders.py", line 33, in __init__
    self.crawl_folders(sequence_length)
  File "/home/dell/EndoSLAM/EndoSfMLearner/datasets/sequence_folders.py", line 42, in crawl_folders
    intrinsics = np.genfromtxt(scene/'cam.txt').astype(np.float32).reshape((3, 3))
ValueError: cannot reshape array of size 1 into shape (3,3)

Can you tell me how to fix the cam.txt?

**Comment by 1484115316** [comment]
I also have the same question. Can I add your WeChat or QQ to ask？
